/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsStageIdRouteImport } from './routes/lessons.$stageId'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as LearnLangCodeRouteImport } from './routes/learn.$langCode'
import { Route as LearnLangCodeFoundationRouteImport } from './routes/learn.$langCode.foundation'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsStageIdRoute = LessonsStageIdRouteImport.update({
  id: '/lessons/$stageId',
  path: '/lessons/$stageId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLangCodeRoute = LearnLangCodeRouteImport.update({
  id: '/learn/$langCode',
  path: '/learn/$langCode',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLangCodeFoundationRoute = LearnLangCodeFoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => LearnLangCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn/$langCode': typeof LearnLangCodeRouteWithChildren
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/lessons/$stageId': typeof LessonsStageIdRoute
  '/learn/$langCode/foundation': typeof LearnLangCodeFoundationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn/$langCode': typeof LearnLangCodeRouteWithChildren
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/lessons/$stageId': typeof LessonsStageIdRoute
  '/learn/$langCode/foundation': typeof LearnLangCodeFoundationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn/$langCode': typeof LearnLangCodeRouteWithChildren
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/lessons/$stageId': typeof LessonsStageIdRoute
  '/learn/$langCode/foundation': typeof LearnLangCodeFoundationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/leaderboard'
    | '/learn/$langCode'
    | '/lesson/$lessonId'
    | '/lessons/$stageId'
    | '/learn/$langCode/foundation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/leaderboard'
    | '/learn/$langCode'
    | '/lesson/$lessonId'
    | '/lessons/$stageId'
    | '/learn/$langCode/foundation'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/leaderboard'
    | '/learn/$langCode'
    | '/lesson/$lessonId'
    | '/lessons/$stageId'
    | '/learn/$langCode/foundation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LearnLangCodeRoute: typeof LearnLangCodeRouteWithChildren
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  LessonsStageIdRoute: typeof LessonsStageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$stageId': {
      id: '/lessons/$stageId'
      path: '/lessons/$stageId'
      fullPath: '/lessons/$stageId'
      preLoaderRoute: typeof LessonsStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$langCode': {
      id: '/learn/$langCode'
      path: '/learn/$langCode'
      fullPath: '/learn/$langCode'
      preLoaderRoute: typeof LearnLangCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$langCode/foundation': {
      id: '/learn/$langCode/foundation'
      path: '/foundation'
      fullPath: '/learn/$langCode/foundation'
      preLoaderRoute: typeof LearnLangCodeFoundationRouteImport
      parentRoute: typeof LearnLangCodeRoute
    }
  }
}

interface LearnLangCodeRouteChildren {
  LearnLangCodeFoundationRoute: typeof LearnLangCodeFoundationRoute
}

const LearnLangCodeRouteChildren: LearnLangCodeRouteChildren = {
  LearnLangCodeFoundationRoute: LearnLangCodeFoundationRoute,
}

const LearnLangCodeRouteWithChildren = LearnLangCodeRoute._addFileChildren(
  LearnLangCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LearnLangCodeRoute: LearnLangCodeRouteWithChildren,
  LessonLessonIdRoute: LessonLessonIdRoute,
  LessonsStageIdRoute: LessonsStageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
